### ISSUE TITLE
Loading spinner graphic needed

### ISSUE THREAD

**Issue by mdcrown** [First10/royalcanin-webdesignlanguage#13]
I see there is an SVG icon already specified as a loading spinner, but it's rather basic and we would rely on each developer implementing the WDL to properly rotate it. Could we provide an animated gif version?

Attached is one I've used on our RCUK website, as an example.
![ring-alt](https://user-images.githubusercontent.com/11058659/26929576-0d9f8276-4c52-11e7-893a-9fd60b18eb22.gif)

**Comment by stephen9001** [comment]
A single class is required to add this asset and make it rotate, so I'm not sure how we can simplify the implementation of this
