### ISSUE TITLE
Gulp Styleguide

### ISSUE THREAD

**Issue by matthewmcclatchie** [First10/royalcanin-webdesignlanguage#2]
After trying out Pattern Lab, I've decided that using our own custom built styleguide generator is the better option. In this branch I'll remove the Pattern Lab files and install and configure the gulp-styleguide files.

**Comment by stephen9001** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI/UX best practices in style guide](https://trello.com/c/OplAPd06/230-ui-ux-best-practices-in-style-guide)
