### ISSUE TITLE
Class naming guidelines

### ISSUE THREAD

**Issue by danharper83** [First10/royalcanin-webdesignlanguage#25]
We need to create guidance notes on class naming conventions so that classes are not removed and the analyst use data attributes instead of class names to identify things and trigger javascript actions.

**Comment by danharper83** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Release documentation](https://trello.com/c/4Q7fOuaJ/131-release-documentation)

**Comment by stephen9001** [comment]
This is being covered by components in other issues, on an individual basis. As discussed with @jmdrawneek
